---
- hosts: OBBservers
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: password update for users
    user:
      name: "{{ item.user }}"
      update_password: always
      password: "{{ item.password | password_hash('sha512') }}"
    with_items:
         - { user: 'T1-anuraj', password: 'Anuraj@2022' }
         - { user: 'T1-xxxx', password: 'xxxx@2022' }
